name: Shell Commands
on: [pull_request]
jobs:
  run-shell-command:
    runs-on: ubuntu-latest
    steps:
      - name: echo a string
        run: echo "hello"
        continue-on-error: true
      - name: multiline script
        if: failure()
        run: |
          node -v
          npm -v
      - name: python cmd
        run: |
           import platform
           print(platform.processor())
        shell: python
